engine/tg_helpers/validation_helper.php
Since all error messages use the same opening and closing html tags, generating them over and over again in loop is not necessary.
=> validation helper: generating opening/closing html tags out of the loop

engine/Pagination.php
Address issue #11 
The $template on line 130 should be $pagination_template.
=> Fix $template undefined in engine/Pagination.php

engine/Core.php
If $abs_file_path is not intended to be used then line 58 should be removed as it is the core file, call str_replace method in a foreach loop may slow down the framework a fraction of a sec.
=> Line 58 $abs_file_path not used

engine/Api.php
Removed some duplicate variables and also variable $fourth_bit doesn't seem to be used.
Api.php in function destroy() Starting at line 1246:
$token_validation_data['endpoint'] = $endpoint_name;
$token_validation_data['module_name'] = $module_name;
$token_validation_data['module_endpoints'] = $module_endpoints;
$input['token'] = $this ->_validate_token($token_validation_data);
$output['token'] = $input['token'];
$token_validation_data['endpoint'] = $endpoint_name;
$token_validation_data['module_name'] = $module_name;
$token_validation_data['module_endpoints'] = $module_endpoints;
$input['token'] = $this->_validate_token($token_validation_data);
$output['token'] = $input['token'];
$fourth_bit = $this->url->segment(4);
=> Removed some duplicate variables in Api.php

engine/get_segments.php
Add support for multiple parameters for custom routes
Handle custom routes  similarly to Codeigniter :
- " (:any) "  for any text slugs
- " (:num) "  for numeric
'hello/(:any)' => 'welcome/index/$1',
'hello/(:any)/(:any)' => 'welcome/index/$1/$2',
'hello/(:any)/(:any)/(:num)' => 'welcome/index/$1/$2/$3'
=> Multiple Parameters for CUSTOM_ROUTES

engine/tg_helpers/validation_helper.php
Mofdify error messages on min_length() and max_length() methods.
=> Misleading error messages from min_length() and max_length() methods in tg_helpers/validation_helper.php

engine/Image.php
Give a more meaningful error message when you try to use the image uploader without having the GD extension loaded in your PHP instance.
=> GD extension error message fix

engine/Model.php
My first Git contribution 🙂
I've updated the insert method SQL query to surround all columns with backticks, eliminating the potential issue of column names that are also database 'reserved' words.
It's also possible that my editor has auto-removed trailing whitespace on some additional lines. I didn't notice before I committed the changes. 😞
=> add backticks to column names on insert query SQL

public/css/trongate.css
Allow scrolling on modal container when the height is greater than the screen 
height of the device. Most apparent on mobile devices.
=> allow scrolling on modal in mobile mode 

README.md
The current link in README.md is parsed to `https://trongate.io/download.%E2%80%8B` by GitHub's markdown interpreter.
=> README.md: fix download link

engine/tg_helpers/validation_helper.php
Originally, $inner_value has been set by using extract() on the $validation_data array. Now, the extract() method call is removed, so $inner_value is undefined.
=> Fix error from rewrite for form field validation.

engine/tg_helpers/url.php, modules/doco/assets/api.json, modules/doco/controllers/Doco.php
There are 3 reasons for this pull request:
1. Removed an ugly PHP 8.2 deprecated method [utf8_encode()](https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated) - _thanks very much PHP Foundation!_ 😟 [#StopBreakingPHP](https://trongate.io/news/display/TWN4GR/its-time-for-the-php-foundation-to-stopbreakingphp)
2. I pulled in this [help_bar fix by framex](https://trongate.io/help_bar/thread/h7W9QyPcsx69) who added full support for non-Latin characters, where previously they were stripped from the input string.
3. I also added a PHP DocBlock to document the method for Intellisense.  If you like them DC, I will proceed to add more throughout the framework as previously discussed and mentioned in [this help_bar post](https://trongate.io/help_bar/thread/SYeCjtEXc47z).  As you will …
=> url_title() fix for non-Latin characters and removed a deprecated method, utf8_encode() introduced in PHP 8.2

engine/tg_helpers/file_helper.php, engine/tg_helpers/url_helper.php, modules/trongate_tokens/controllers/Trongate_tokens.php
Replaced the random string generator with a cryptographically secure one. And made the file helper and Trongate tokens module use the new secure generator. This closes the doors for some vulnerabilities that rely upon these insecure generators.
More information about it: https://owasp.org/www-community/vulnerabilities/Insecure_Randomness
=> Replaced insecure string generator with a secure one

modules/trongate_users/trongate_user_levels/controllers/Trongate_user_levels.php
There is no need for an else clause here, we can just initialize the $user_level variable before the if statement to $user_level = '';
less code, more readable?
=> No need for an else clause, just initialize $user_level before if statement.

engine/Trongate.php
Changed `string|null` to `?string` which is not a valid syntax in PHP
Please note that this syntax is valid in PHP 7.1 and later versions.
=> Fixed some return types that were giving syntax errors

engine/Trongate.php
Changed `protected ?string $module_name;` to `protected ?string $module_name = '';`
Which fixes an error when `parent::__construct();` not included in `__construct()` of a sub module with a normal `$this->view()`
Error message > `Uncaught Error: Typed property Trongate::$module_name must not be accessed before initialization`
Also added links to the Trongate docs for view() and template() methods
=> Fixed error being thrown when using normal view from a sub module

engine/tg_helpers/form_helper.php
It appeared that the newer version of form_helper.php is generating a new CSRF token each time form_close() is called. This was the reason for the issue we were facing with the single image uploader, as a new token was being generated before the form was submitted, leading to a mismatch during validation. Therefore the fix would be to only generate a CSRF token once per session.  Thanks to michidesign for spotting this and letting us know via the [Help_Bar on Trongate.io](https://trongate.io/help_bar_threads/display/KSsFCTJUTDrkWz56)
Please give Trongate a star on GitHub!
=> Minor fix to CSRF token

engine/Core.php, engine/Standard_endpoints.php
The "delete_one()" method in "Standard_endpoints.php" was not sending an 'id' to delete in the passed '$input' array which was being checked in the "_make_sure_delete_allowed" method from the **Category Builder** module on [the Module Market](https://trongate.io/module-market).
This fix:
1. Ensures proper handling of subcategories, preventing the deletion of a parent category when subcategories exist.
2. Resolves the issue of subcategories remaining in the table without appearing in categories/manage after deleting a main category.
3. Enhances Category Builder reliability.
=> Add ID Parameter for Deletion in delete_one() Function

engine/Core.php
- Updated code to allow segment 3 to pass "0" without being treated as an empty string.
In the previous code, when checking if segment 3 was set and processing its value, there was an oversight that resulted in treating "0" as an empty string. This issue has been addressed in the updated code.
I apologise for the oversight in the previous code, and appreciate your understanding.
=> Fix handling of '0' in segment 3 to prevent empty string assignment

engine/Modules.php
Fix deprecation warning in Modules.php by using an array to store module instances
Resolves issue with dynamic property creation being deprecated in PHP 8.2 and later. 
Updated load method to use an array to store module instances, avoiding dynamic property creation. 
This change ensures compatibility with PHP 8.2 and later versions.
```
Deprecated
: Creation of dynamic property Modules::$trongate_pages is deprecated in
D:\xampp\htdocs\testapp\engine\Modules.php
on line
67
```
Tested on PHP 8.2.14, 8.2.19 and 8.3.7 (latest build of PHP) and is working fine with DC's new homepage update now using Trongate Pages 👍
=> fixed a Dynamic Property message on load() method

engine/File_validation.php, engine/Image.php
Addressed the following warnings and issues in File_validation.php and Image.php:
- PHP Deprecated: Implicit conversion from float to int
- Changed type cast from int to float for **$file_size** and **$max_size**.
- Changed type cast from int to float for **$width** and **$height**.
- Repaired PHP Intelephense syntax highlighting issues in Image.php:
- Expected type 'GdImage'. Found 'resource|null'. intelephense(P1006)
- Changed docblock to: * @var resource|**GdImage**|null
- Expected type 'GdImage'. Found 'resource'. intelephense(P1006)
- Changed docblock to: * @param resource|**GdImage** $resource
=> Fix deprecation warnings and syntax highlighting issues in File_validation.php and Image.php

modules/trongate_administrators/views/tg_admin_template.php
Proposed bug fix for https://trongate.io/help_bar_threads/display/aQ3DRXGaQubahmPR
Added an additional condition in the view file. 
Now, in addition to the existing checks, if the 2nd URL segment is an empty string/not present, do not display the &lt;div> with ID "top-gutter".
=> 'Error using trongate_administrators as the home page'

engine/Core.php, engine/File.php
File.php : correct variable names in write() function.
Core.php:
The new sanitize_file_path() function prevents child module assets from being found. 
This modification fixes that issue and returns the child module asset path, making the serve_child_module_asset() function redundant so a good chunk of code can be removed from Core.php
I've added a boolean variable $is_child_module to sanitize_file_path() so that we can loop back, setting it to true to check the path to a child module asset if nothing's found in the parent module.
I've also added a 404 http response code if the file path is invalid.
=> Fix to Core.php to permit serving child module assets

engine/Core.php, engine/Model.php
Some efficiency improvements when serving module assets - helpful when dealing with larger files.
1) readfile() vs file_get_contents() streams larger files and avoids the need to read the whole file into memory first. 
2) added 304 Not Modified response to HTTP_IF_MODIFIED_SINCE request. Avoids having to send files if client just wants to check that their cached copy is still valid.
3) is_file() checks if it's a valid file vs file_exists() which returns true for files and directories
4) 403 response code to .php and api.json files is the more common response to attempts to access files that shouldn't be
5) Add Last-Modified header when sending file
=> Efficiency improvements to serve_module_asset()
